import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/Navbar";
import Categories from "@/components/Categories/Categories";
import Footer from "@/components/Footer/Footer";
import CopyRight from "@/components/CopyRight/CopyRight";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Categories />
        {children}
        <Footer />
        <CopyRight />
      </body>
    </html>
  );
}
